#!/usr/bin/env python3
"""build_repo_tools.py — orchestrate the repo factory across rsi's certified tooling,
then emit the BACKBONE registry that /rsi loads.

For each repo in knowledge/certifications.json at/above --min-tier, run repo_factory
(KG + SKILL.md), then write:
  • skills/registry.json  — the always-loaded catalog (backbone): slug → trigger · KG · tier
  • skills/README.md      — a human/agent index of every minted skill
Progressive disclosure is native: each skills/<slug>/SKILL.md body loads only when its
frontmatter description matches the task; the registry is the compact backbone index.

  build_repo_tools.py [--min-tier verified|certified] [--limit N] [--enrich] [--registry-only]
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys

from rsidata import ROOT

TIER_RANK = {"🥉 Listed": 0, "🥈 Verified": 1, "🥇 RSI-Certified": 2}
MIN = {"listed": 0, "verified": 1, "certified": 2}


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def targets(min_tier: str) -> list[dict]:
    certs = json.loads((ROOT / "knowledge" / "certifications.json").read_text())["certifications"]
    bar = MIN[min_tier]
    return [c for c in certs if c.get("kind") in ("repo", "skill", "mcp", "workflow")
            and c.get("url", "").startswith("https://github.com/")
            and TIER_RANK.get(c["tier"], 0) >= bar]


def build_registry() -> dict:
    """Scan skills/*/SKILL.md → the backbone catalog (trigger + KG + tier per skill)."""
    entries = []
    for sk in sorted((ROOT / "skills").glob("*/SKILL.md")):
        slug = sk.parent.name
        text = sk.read_text()
        name = (re.search(r"^name:\s*(.+)$", text, re.M) or [None, slug])[1].strip()
        tier = (re.search(r"tier:\s*(.+?)\.?\)", text) or re.search(r"tier:\s*\*\*(.+?)\*\*", text))
        tier = tier.group(1).strip() if tier else "unrated"
        kg = ROOT / "knowledge" / "repos" / slug / "graph.json"
        entries.append({
            "slug": slug, "name": name, "tier": tier,
            "skill": f"skills/{slug}/SKILL.md",
            "kg": f"knowledge/repos/{slug}/graph.json" if kg.exists() else None,
        })
    return {"count": len(entries), "skills": entries}


def render_index(reg: dict) -> str:
    L = ["# 🧰 rsi Certified Toolsets — the backbone registry", "",
         "Every top repo cited by rsi is minted into an **agentic skill** (+ a knowledge graph) "
         "by `scripts/build_repo_tools.py`. `/rsi` loads this index as **backbone**; each skill's "
         "body loads on-demand (**progressive disclosure**) when its trigger matches your task.", "",
         f"**{reg['count']} skills** · machine-readable: [`registry.json`](registry.json)", "",
         "| Skill | Tier | Skill file | Knowledge graph |", "|-------|------|-----------|-----------------|"]
    for e in reg["skills"]:
        kg = f"[`graph.json`](../{e['kg']})" if e["kg"] else "—"
        L.append(f"| **{e['name']}** | {e['tier']} | [`SKILL.md`]({e['slug']}/SKILL.md) | {kg} |")
    L += ["", "<sub>Generated by scripts/build_repo_tools.py — do not hand-edit.</sub>"]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-tier", choices=["listed", "verified", "certified"], default="verified")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--enrich", action="store_true")
    ap.add_argument("--registry-only", action="store_true", help="skip minting; just rebuild the index")
    args = ap.parse_args()

    if not args.registry_only:
        tgts = targets(args.min_tier)
        if args.limit:
            tgts = tgts[:args.limit]
        print(f"minting {len(tgts)} repo(s) at ≥{args.min_tier}", file=sys.stderr)
        for c in tgts:
            cmd = [sys.executable, str(ROOT / "scripts" / "repo_factory.py"),
                   "--target", c["url"], "--tier", c["tier"]]
            if args.enrich:
                cmd.append("--enrich")
            r = subprocess.run(cmd)
            if r.returncode != 0:
                print(f"  ! factory failed for {c['url']}", file=sys.stderr)

    reg = build_registry()
    (ROOT / "skills").mkdir(exist_ok=True)
    (ROOT / "skills" / "registry.json").write_text(json.dumps(reg, indent=2, ensure_ascii=False))
    (ROOT / "skills" / "README.md").write_text(render_index(reg))
    print(f"✓ backbone registry: {reg['count']} skill(s) → skills/registry.json + skills/README.md", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
